### ISSUE TITLE
DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry

### ISSUE THREAD

**Issue by freon27** [remackgeek/elements-zone-strategy#1]
Hi,

First of all thanks!  This module made my change detection work which was the thing that was putting me off using Angular Elements.

I have noticed that using this causes the above error to reappear when I try to load a second Angular Element (I only use one at a time but I need to be able to switch them). 

I had this problem before but I hacked my way around it by messing with webpackJsonP. When I use your module, this no longer works and I can't really work out why it has this effect.

Do you have any ideas what might be causing that?

**Comment by remackgeek** [comment]
@freon27, Sorry I missed this before. I ran into what may be the same issue.  I fixed my issue in the 6.0.3 version (published July 8). Have you tried that version?

**Comment by jathanaselos** [comment]
Having the same problem.    I have multiple angular elements in my app.   I only show them one at a time.   I can't define an Element Zone Strategy for more than 1 element. 

Is there any suggested workaround?    

Thank you in advance for any help.

**Comment by jathanaselos** [comment]
(DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry)

**Comment by remackgeek** [comment]
Could you provide a snippet of what you mean? Since the strategy takes a specific component in the constructor, you need to make a new one for each component/element. Something like:

`const strategyFactory = new ElementZoneStrategyFactory(HelloComponent, this.injector);`
`const helloElement = createCustomElement(HelloComponent, { injector: this.injector, strategyFactory });`
`customElements.define('my-hello', helloElement);`
`const strategyFactory2 = new ElementZoneStrategyFactory(Hello2Component, this.injector);`
`const hello2Element = createCustomElement(Hello2Component, { injector: this.injector, strategyFactory2});`
`customElements.define('my-hello2', hello2Element);`

**Comment by jathanaselos** [comment]
Thank you so much for the quick reply.


I'm using Angular 8 for two basic components.  I'm declaring the element zone strategy factory in my app.module.ts.

When I try creating multiple strategy factory's, I receive a strange syntax error (attached) and the attached compile time error.

The only workaround I know is to put all of my elements in 1 master element and have only 1 element strategy factory and pass a 'mode' attribute but it's very hackish obviously.    


SIDE NOTE:   ElementZoneStrategyFactory is the only reason I am able to take advantage of Angular Elements for my project..    this project deserves A LOT of credit.



![Compile_MultipleStrategyFactoryError](https://user-images.githubusercontent.com/5253386/65773488-6ad86580-e10a-11e9-9e12-0e8a46bf68f3.JPG)




![MultipleStrategyFactoryError](https://user-images.githubusercontent.com/5253386/65773350-23ea7000-e10a-11e9-8e15-68ed0e5ac340.JPG)
compile

**Comment by remackgeek** [comment]
Ack. That's what I get for copy/pasting in hurry. The second one needs explicit property assignment. Try this:
`const hello2Element = createCustomElement(Hello2Component, { injector: this.injector, strategyFactory: strategyFactory2});`

**Comment by jathanaselos** [comment]
Ack... I should have figured that out.   Thank you, worked like a charm.
